nav:
    - Introduction: index.md
    - Optimal-substructure: Optimal-substructure.md
    
    - Optimization-summary: Optimization-summary.md
    - Dynamic-programming-VS-search-algorithm-VS-greedy-algorithm: Dynamic-programming-VS-search-algorithm-VS-greedy-algorithm.md