nav:
    - Backtracking: Backtracking.md
    - Sudoku-solving-algorithms: Sudoku-solving-algorithms.md
    - Permutation-and-combination: Permutation-and-combination
    - Reading-list: Reading-list.md